#!/bin/bash
bat_res=$(acpi -b 0)
bat_amt=$(echo $bat_res | egrep -o "[0-9]*%" | sed -e "s/%//g")
bat_sts="$(echo $bat_res | egrep -o 'Charging')"
bat_a=
bat_b=
bat_c=
bat_d=
bat_e=
bat_chr=

res=""
col="#FFFFFF"

if [[ "$(echo $bat_amt | wc -c)" -gt 1 ]]; then

	if [[ $bat_amt -ge 80 && $bat_amt -le 100 ]]; then res=$bat_a; col="#00FF00"; fi
	if [[ $bat_amt -ge 60 && $bat_amt -lt 80  ]]; then res=$bat_b; col="#88FF00"; fi
	if [[ $bat_amt -ge 40 && $bat_amt -lt 60  ]]; then res=$bat_c; col="#FFFF00"; fi
	if [[ $bat_amt -ge 20 && $bat_amt -lt 40  ]]; then res=$bat_d; col="#FF8800"; fi
	if [[ $bat_amt -ge 0  && $bat_amt -lt 20  ]]; then res=$bat_e; col="#FF0000"; fi

	if [[ $bat_sts == "Charging" ]]; then res="$res $bat_chr"; fi
	res="$res $bat_amt%"

	echo $res
	echo $res
	echo $col

fi